spring.application.name=product-api
# ruta base del api
server.servlet.context-path=/api/v1
# topic de kafka
spring.cloud.stream.bindings.commands-out-0.destination=products.commands
spring.cloud.stream.bindings.commands-out-0.content-type=application/json

spring.cloud.function.definition=handleReplies
spring.cloud.stream.bindings.handleReplies-in-0.destination=products.replies
spring.cloud.stream.bindings.handleReplies-in-0.content-type=application/json
spring.cloud.stream.bindings.handleReplies-in-0.group=product-api
spring.cloud.stream.kafka.bindings.handleReplies-in-0.consumer.startOffset=latest
# broker de kafka
spring.cloud.stream.kafka.binder.brokers=kafka:19092
